@Ticketing.Command_HostAddress = http://localhost:5001

POST {{Ticketing.Command_HostAddress}}/api/ticket/
Accept: application/json
Content-Type: application/json

{
  "username": "Alan Cuevas",
  "typeError": "This is a sample ticket description. (Error System)",
  "detailError": "The system encountered an unexpected error while processing the request."
}